server:
  port: 8083

spring:
  application:
    name: invest-service
  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888/}"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  packages-to-scan: org.murat.orion.invest_service
  show-actuator: false

info:
  title: Invest Service API
  description: API documentation for Invest Service
  version: v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
