server:
  port: 8761 # Eureka'n?n standart portu budur.

spring:
  application:
    name: discovery-server
  config:
    import: "optional:configserver:http://localhost:8888/"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0 #